import { DocumentHeader, Footer, LegalShell } from "../site-components";
import { siteConfig } from "../site-config";

export const metadata = { title: "Política de Privacidade" };

export default function Privacy() {
  return <LegalShell><main className="document"><DocumentHeader eyebrow="PRIVACIDADE" title="Política de Privacidade" lead="Esta política explica de forma clara como o DocVia trata dados pessoais quando você cria uma conta, envia documentos e utiliza as análises." />
    <div className="legal-grid"><aside className="side"><strong>Controlador</strong>{siteConfig.controller}<br />Contato: {siteConfig.email}</aside><article className="copy">
      <section><h2>1. Quem somos</h2><p>O controlador dos dados tratados pelo aplicativo DocVia é <strong>{siteConfig.controller}</strong>. Dúvidas e solicitações relacionadas à privacidade podem ser enviadas para <strong>{siteConfig.email}</strong>.</p></section>
      <section><h2>2. Dados que tratamos</h2><ul><li>dados da conta, como nome, e-mail, senha protegida por hash e data de cadastro;</li><li>documentos ou textos enviados voluntariamente, seus nomes, tipo e conteúdo extraído;</li><li>resultados produzidos, incluindo resumos, prazos, custos, alertas e itens de ação;</li><li>preferências de notificação armazenadas no aparelho;</li><li>registros técnicos mínimos de segurança, funcionamento e limites de uso.</li></ul><p>O DocVia não solicita acesso amplo à sua galeria. A seleção de arquivos ocorre pelo seletor do sistema, e a câmera é usada apenas quando você escolhe digitalizar um documento.</p></section>
      <section><h2>3. Para que usamos</h2><p>Usamos os dados para criar e proteger sua conta; receber e extrair texto de documentos; gerar a análise solicitada; identificar prazos; permitir exportação e exclusão; prevenir abuso; recuperar senha; e manter o serviço seguro.</p><p>As bases legais aplicáveis podem incluir execução do serviço solicitado, consentimento quando exigido, legítimo interesse em segurança e cumprimento de obrigação legal.</p></section>
      <section><h2>4. Inteligência artificial</h2><p>Para gerar resumos e apontamentos, o texto necessário é enviado ao provedor de inteligência artificial configurado pelo DocVia. A versão de produção somente será habilitada em modalidade contratual na qual os dados enviados pela API não sejam utilizados para melhorar modelos ou produtos do provedor.</p><div className="notice">A inteligência artificial pode errar ou omitir informações. O resultado é informativo e não substitui aconselhamento jurídico, financeiro, contábil ou profissional.</div></section>
      <section><h2>5. Fornecedores e transferências</h2><p>Podemos utilizar fornecedores de infraestrutura, banco de dados, armazenamento privado, e-mail transacional, monitoramento e inteligência artificial. Alguns podem processar dados fora do Brasil. Nesses casos adotamos contratos, controles de acesso e medidas compatíveis com a LGPD.</p><p>Não vendemos documentos nem dados pessoais e não os utilizamos para publicidade comportamental.</p></section>
      <section><h2>6. Armazenamento e retenção</h2><p>Documentos, textos e análises permanecem disponíveis enquanto sua conta estiver ativa ou até você excluir o documento. Ao excluir a conta, removemos os dados associados dos sistemas ativos, ressalvadas retenções estritamente necessárias por obrigação legal, prevenção a fraude ou cópias de segurança com ciclo limitado.</p><p>Tokens de recuperação expiram em 15 minutos. Tokens de sessão possuem validade limitada e podem ser revogados.</p></section>
      <section><h2>7. Segurança</h2><p>Adotamos comunicação HTTPS, armazenamento privado, autenticação, limites de requisição, segregação por usuário e redução de dados em logs. Nenhum sistema é completamente invulnerável; incidentes relevantes serão tratados conforme a legislação aplicável.</p></section>
      <section><h2>8. Seus direitos</h2><p>Você pode solicitar confirmação de tratamento, acesso, correção, portabilidade quando aplicável, informações sobre compartilhamento, revogação de consentimento e exclusão. O aplicativo oferece exportação e exclusão de conta na área de perfil.</p></section>
      <section><h2>9. Crianças e adolescentes</h2><p>O DocVia não é direcionado a menores de 18 anos e não deve ser utilizado para enviar dados de crianças ou adolescentes sem a autorização e a base legal adequadas.</p></section>
      <section><h2>10. Alterações e contato</h2><p>Esta política pode ser atualizada para refletir mudanças no serviço ou na legislação. A data e a versão mais recentes aparecerão no topo. Contato: <strong>{siteConfig.email}</strong>.</p></section>
    </article></div></main><Footer /></LegalShell>;
}
