import React from 'react';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { House, FileText, Plus, CalendarClock, UserRound } from 'lucide-react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Animated, { Easing, useAnimatedStyle, useSharedValue, withTiming } from 'react-native-reanimated';
import { colors, shadows } from '../theme';
import { useInteractiveState } from './ui';

const TABS = [{ key: 'home', label: 'Início', Icon: House }, { key: 'documents', label: 'Documentos', Icon: FileText }, { key: 'deadlines', label: 'Prazos', Icon: CalendarClock }, { key: 'profile', label: 'Perfil', Icon: UserRound }];
function Tab({ tab, active, onPress }) { const interaction = useInteractiveState(); const color = active ? colors.primary : interaction.hovered ? colors.text : '#8A93A6'; return <Pressable {...interaction.bind} onPress={onPress} style={[styles.tab, interaction.hovered && styles.hover]} accessibilityRole="tab" accessibilityState={{ selected: active }} accessibilityLabel={tab.label}><View style={[styles.activeBg, active && styles.activeBgOn]}><tab.Icon size={22} strokeWidth={1.9} color={color} /></View><Text style={[styles.label, { color }]}>{tab.label}</Text></Pressable>; }
export default function FloatingNavV2({ active, navigate }) { const insets = useSafeAreaInsets(); const selectedIndex = Math.max(0, TABS.findIndex((tab) => tab.key === active)); const position = useSharedValue(selectedIndex); position.value = withTiming(selectedIndex, { duration: 220, easing: Easing.out(Easing.cubic) }); const indicator = useAnimatedStyle(() => ({ transform: [{ translateX: position.value * 76 }] })); const go = (key) => { if (Platform.OS !== 'web') Haptics.selectionAsync().catch(() => undefined); navigate(key); }; return <View pointerEvents="box-none" style={[styles.outer, { bottom: insets.bottom + 12 }]}><View style={styles.bar}><Animated.View style={[styles.indicator, indicator]} />{TABS.slice(0, 2).map(tab => <Tab key={tab.key} tab={tab} active={active === tab.key} onPress={() => go(tab.key)} />)}<View style={styles.fabSlot}><Pressable onPress={() => go('upload')} accessibilityRole="button" accessibilityLabel="Enviar documento" style={({ pressed, hovered }) => [styles.fab, pressed && styles.fabPressed, hovered && styles.fabHover]}><Plus color={colors.white} size={28} strokeWidth={2} /></Pressable></View>{TABS.slice(2).map(tab => <Tab key={tab.key} tab={tab} active={active === tab.key} onPress={() => go(tab.key)} />)}</View></View>; }
const styles = StyleSheet.create({ outer: { position: 'absolute', left: 16, right: 16 }, bar: { height: 64, borderRadius: 28, backgroundColor: '#14161B', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', overflow: 'visible', ...shadows.nav }, tab: { width: 76, height: 62, alignItems: 'center', justifyContent: 'center', gap: 3, zIndex: 2 }, hover: { backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 16 }, activeBg: { width: 38, height: 31, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, activeBgOn: { backgroundColor: 'rgba(59,130,246,0.14)' }, indicator: { position: 'absolute', top: 8, left: 19, width: 38, height: 31, borderRadius: 16, backgroundColor: 'rgba(59,130,246,0.14)' }, label: { fontSize: 11, fontWeight: '500' }, fabSlot: { width: 76, alignItems: 'center', overflow: 'visible' }, fab: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', transform: [{ translateY: -18 }], shadowColor: colors.primary, shadowOpacity: .45, shadowRadius: 14, shadowOffset: { width: 0, height: 6 }, elevation: 9 }, fabPressed: { transform: [{ translateY: -18 }, { scale: .94 }] }, fabHover: { backgroundColor: '#5B94F8', transform: [{ translateY: -20 }] } });
