import React, { useEffect } from 'react';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { CalendarClock, FileText, House, Plus, UserRound } from 'lucide-react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Animated, { Easing, useAnimatedStyle, useSharedValue, withTiming } from 'react-native-reanimated';
import { colors, shadows } from '../theme';
import { useInteractiveState } from './ui';

const tabs = [{ key: 'home', label: 'Início', Icon: House, offset: 0 }, { key: 'documents', label: 'Documentos', Icon: FileText, offset: 76 }, { key: 'deadlines', label: 'Prazos', Icon: CalendarClock, offset: 228 }, { key: 'profile', label: 'Perfil', Icon: UserRound, offset: 304 }];
function Tab({ item, active, onPress }) { const state = useInteractiveState(); const color = active ? colors.primary : state.hovered ? colors.text : '#8A93A6'; return <Pressable {...state.bind} onPress={onPress} accessibilityRole="tab" accessibilityState={{ selected: active }} accessibilityLabel={item.label} style={[styles.tab, state.hovered && styles.tabHover]}><item.Icon size={22} strokeWidth={1.9} color={color} /><Text style={[styles.label, { color }]}>{item.label}</Text></Pressable>; }
export default function FloatingNav({ active, navigate }) { const insets = useSafeAreaInsets(); const item = tabs.find((tab) => tab.key === active) || tabs[0]; const translateX = useSharedValue(item.offset); useEffect(() => { translateX.value = withTiming(item.offset, { duration: 220, easing: Easing.out(Easing.cubic) }); }, [item.offset, translateX]); const indicatorStyle = useAnimatedStyle(() => ({ transform: [{ translateX: translateX.value }] })); const open = (key) => { if (Platform.OS !== 'web') Haptics.selectionAsync().catch(() => undefined); navigate(key); }; return <View pointerEvents="box-none" style={[styles.outer, { bottom: insets.bottom + 12 }]}><View style={styles.bar}><Animated.View pointerEvents="none" style={[styles.indicator, indicatorStyle]} />{tabs.slice(0, 2).map((tab) => <Tab key={tab.key} item={tab} active={active === tab.key} onPress={() => open(tab.key)} />)}<View style={styles.fabSlot}><Pressable accessibilityRole="button" accessibilityLabel="Enviar documento" onPress={() => open('upload')} style={({ pressed, hovered }) => [styles.fab, pressed && styles.fabPressed, hovered && styles.fabHover]}><Plus size={28} color={colors.white} strokeWidth={2} /></Pressable></View>{tabs.slice(2).map((tab) => <Tab key={tab.key} item={tab} active={active === tab.key} onPress={() => open(tab.key)} />)}</View></View>; }
const styles = StyleSheet.create({ outer: { position: 'absolute', left: 16, right: 16 }, bar: { height: 64, borderRadius: 28, backgroundColor: '#14161B', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', flexDirection: 'row', overflow: 'visible', ...shadows.nav }, indicator: { position: 'absolute', top: 7, left: 19, width: 38, height: 31, borderRadius: 16, backgroundColor: 'rgba(59,130,246,0.14)' }, tab: { width: 76, height: 63, alignItems: 'center', justifyContent: 'center', gap: 3, zIndex: 1, borderRadius: 16 }, tabHover: { backgroundColor: 'rgba(255,255,255,0.06)' }, label: { fontSize: 11, fontWeight: '500' }, fabSlot: { width: 76, alignItems: 'center', justifyContent: 'center', overflow: 'visible', zIndex: 2 }, fab: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', transform: [{ translateY: -18 }], shadowColor: colors.primary, shadowOpacity: .45, shadowRadius: 14, shadowOffset: { width: 0, height: 6 }, elevation: 10 }, fabPressed: { transform: [{ translateY: -18 }, { scale: .94 }] }, fabHover: { transform: [{ translateY: -20 }], backgroundColor: '#5B94F8' } });
