import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { X } from 'lucide-react-native';
import Animated, { useAnimatedStyle, useSharedValue, withSpring } from 'react-native-reanimated';
import { colors, common, motion, radii, shadows, spacing, typography } from '../theme';

export function useInteractiveState() { const [hovered, setHovered] = useState(false); const [pressed, setPressed] = useState(false); const [focused, setFocused] = useState(false); return { hovered, pressed, focused, bind: { onHoverIn: () => setHovered(true), onHoverOut: () => setHovered(false), onPressIn: () => setPressed(true), onPressOut: () => setPressed(false), onFocus: () => setFocused(true), onBlur: () => setFocused(false) } }; }
export function Screen({ children, style, scroll = true, refreshControl }) { const { ScrollView } = require('react-native'); const Container = scroll ? ScrollView : View; return <View style={common.screen}><Container contentContainerStyle={[styles.screen, style]} refreshControl={refreshControl} keyboardShouldPersistTaps="handled">{children}</Container></View>; }
export function Button({ title, onPress, variant = 'primary', loading, disabled, style, accessibilityLabel }) { const state = useInteractiveState(); const scale = useSharedValue(1); useEffect(() => { scale.value = withSpring(state.pressed ? .98 : state.hovered ? 1.02 : 1, motion.spring); }, [scale, state.pressed, state.hovered]); const animated = useAnimatedStyle(() => ({ transform: [{ translateY: state.pressed ? 1 : state.hovered ? -2 : 0 }, { scale: scale.value }] })); return <Animated.View style={[animated, style]}><Pressable {...state.bind} disabled={disabled || loading} onPress={onPress} accessibilityRole="button" accessibilityLabel={accessibilityLabel || title} style={[styles.button, styles[variant], (disabled || loading) && styles.disabled, state.hovered && styles.hover]}>{loading ? <ActivityIndicator color={variant === 'secondary' || variant === 'ghost' ? colors.text : colors.white} /> : <Text style={[styles.buttonText, styles[`${variant}Text`]]}>{title}</Text>}</Pressable></Animated.View>; }
export function Input({ label, error, icon, ...props }) { const [focused, setFocused] = useState(false); return <View style={styles.inputWrap}><Text style={[styles.inputLabel, (focused || props.value) && styles.labelActive]}>{label}</Text><View style={[styles.inputBox, focused && styles.inputFocus, error && styles.inputError]}>{icon && <Text style={styles.inputIcon}>{icon}</Text>}<TextInput {...props} placeholderTextColor={colors.muted} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} style={styles.input} accessibilityLabel={label} /></View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}</View>; }
export function Card({ children, style }) { return <View style={[common.card, style]}>{children}</View>; }
export function Badge({ status }) { const map = { done: ['Pronto', colors.success], completed: ['Pronto', colors.success], pending: ['Na fila', colors.warning], processing: ['Processando', colors.primary], error: ['Erro', colors.error], failed: ['Erro', colors.error] }; const [label, color] = map[status] || [status || 'Novo', colors.muted]; return <View style={[styles.badge, { backgroundColor: `${color}22` }]}><Text style={[styles.badgeText, { color }]}>{label}</Text></View>; }
export function Skeleton({ height = 18, width = '100%' }) { return <View accessibilityLabel="Carregando" style={[styles.skeleton, { height, width }]} />; }
export function EmptyState({ title = 'Nada por aqui ainda', text, action }) { return <View style={styles.empty}><Text style={styles.emptyIcon}>⌁</Text><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{text || 'Quando houver novidades, elas aparecerão aqui.'}</Text>{action}</View>; }
export function ErrorState({ error, retry }) { return <EmptyState title="Não foi possível carregar" text={error || 'Verifique sua conexão e tente novamente.'} action={<Button title="Tentar novamente" onPress={retry} variant="secondary" />} />; }
export function Sheet({ visible, title, children, onClose }) { return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.overlay} onPress={onClose}><Pressable accessibilityViewIsModal style={styles.sheet} onPress={() => {}}><View style={styles.handle} /><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Fechar ${title}`} hitSlop={10} onPress={onClose} style={styles.sheetClose}><X size={18} color="#B8BAC7" /></Pressable></View>{children}</Pressable></Pressable></Modal>; }
export function Toast({ message }) { return message ? <View style={styles.toast} accessibilityLiveRegion="polite"><Text style={styles.toastText}>{message}</Text></View> : null; }
const styles = StyleSheet.create({ screen: { paddingTop: spacing.xl, paddingBottom: 128, paddingHorizontal: spacing.lg, gap: spacing.md }, button: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radii.md, paddingHorizontal: spacing.lg, ...shadows.card }, primary: { backgroundColor: '#6657F2' }, secondary: { backgroundColor: '#111219', borderColor: '#292B35', borderWidth: 1 }, ghost: { backgroundColor: 'transparent' }, destructive: { backgroundColor: colors.error }, buttonText: { fontWeight: '700', fontSize: 15 }, primaryText: { color: '#FFFFFF' }, destructiveText: { color: colors.white }, secondaryText: { color: '#F1F1F6' }, ghostText: { color: '#A99FFF' }, disabled: { opacity: .45 }, hover: { shadowOpacity: .34 }, inputWrap: { gap: 5 }, inputLabel: { color: colors.muted, fontSize: 13, fontWeight: '600' }, labelActive: { color: colors.primary }, inputBox: { flexDirection: 'row', alignItems: 'center', minHeight: 52, paddingHorizontal: spacing.sm, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, inputFocus: { borderColor: colors.primary }, inputError: { borderColor: colors.error }, input: { flex: 1, color: colors.text, fontSize: 16, paddingVertical: 10 }, inputIcon: { color: colors.muted, fontSize: 18, marginRight: 8 }, error: { color: colors.error, fontSize: 12 }, badge: { alignSelf: 'flex-start', borderRadius: radii.pill, paddingHorizontal: 9, paddingVertical: 5 }, badgeText: { ...typography.caption, fontSize: 10 }, skeleton: { backgroundColor: colors.surfaceRaised, borderRadius: radii.sm, opacity: .75 }, empty: { alignItems: 'center', paddingVertical: spacing.xxxl, gap: spacing.sm }, emptyIcon: { fontSize: 38, color: colors.primary }, emptyTitle: { color: colors.text, ...typography.h2 }, emptyText: { color: colors.muted, textAlign: 'center', ...typography.body }, overlay: { flex: 1, backgroundColor: '#000000B8', justifyContent: 'flex-end' }, sheet: { width: '100%', backgroundColor: '#111219', borderTopWidth: 1, borderColor: '#292B35', borderTopLeftRadius: 25, borderTopRightRadius: 25, paddingHorizontal: 28, paddingTop: 14, paddingBottom: 42, gap: 14 }, handle: { alignSelf: 'center', width: 32, height: 4, borderRadius: 4, backgroundColor: '#9FA8BD', marginBottom: 5 }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sheetTitle: { color: '#F4F4F8', fontSize: 20, fontWeight: '800', letterSpacing: -.25 }, sheetClose: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#2B2D37' }, toast: { position: 'absolute', bottom: 100, left: 20, right: 20, backgroundColor: colors.surfaceRaised, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, padding: spacing.md, ...shadows.card }, toastText: { color: colors.text, textAlign: 'center' } });
