import React, { useState } from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Button, Input, Screen } from '../components/ui';
import { authApi } from '../services/api';
import { colors, common, spacing } from '../theme';
export function Login({ login, go }) { const [email, setEmail] = useState(''); const [senha, setSenha] = useState(''); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async () => { if (!email || !senha) return setError('Informe seu e-mail e senha.'); setLoading(true); try { await login(email, senha); } catch (e) { setError(e.message); } finally { setLoading(false); } }; return <Screen style={styles.auth}><View><Text style={styles.brand}>DOCVIA</Text><Text style={common.title}>Entenda antes de assinar.</Text><Text style={common.subtitle}>Seus documentos, explicados com clareza.</Text></View><Input label="E-mail" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" error={error} /><Input label="Senha" value={senha} onChangeText={setSenha} secureTextEntry={!show} icon={show ? '◉' : '○'} /><Button title="Entrar" loading={loading} onPress={submit} /><Button title="Esqueci minha senha" variant="ghost" onPress={() => go('forgot')} /><Text style={styles.center}>Ainda não tem conta?</Text><Button title="Criar conta" variant="secondary" onPress={() => go('register')} /></Screen>; }
export function Register({ login, go }) { const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [senha, setSenha] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async () => { if (!name || !email || senha.length < 8) return setError('Preencha os dados; a senha precisa de 8 caracteres.'); setLoading(true); try { await authApi.register(name, email, senha); await login(email, senha); } catch (e) { setError(e.message); } finally { setLoading(false); } }; return <Screen style={styles.auth}><Text style={common.title}>Crie sua conta</Text><Text style={common.subtitle}>Comece a entender seus documentos hoje.</Text><Input label="Nome" value={name} onChangeText={setName} /><Input label="E-mail" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" /><Input label="Senha" value={senha} onChangeText={setSenha} secureTextEntry error={error} /><Button title="Criar conta" loading={loading} onPress={submit} /><Button title="Já tenho conta" variant="ghost" onPress={() => go('login')} /></Screen>; }
export function Forgot({ go }) { const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false); return <Screen style={styles.auth}><Text style={common.title}>Recupere sua senha</Text><Text style={common.subtitle}>Enviaremos instruções para seu e-mail.</Text><Input label="E-mail" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" /><Button title="Enviar instruções" loading={loading} onPress={async () => { setLoading(true); try { await authApi.forgotPassword(email); setMessage('Se este e-mail estiver cadastrado, as instruções foram enviadas.'); } catch (e) { setMessage(e.message); } finally { setLoading(false); } }} />{message ? <Text style={styles.message}>{message}</Text> : null}<Button title="Voltar ao login" variant="ghost" onPress={() => go('login')} /></Screen>; }
export function Reset({ go }) { const [token, setToken] = useState(''); const [senha, setSenha] = useState(''); const [message, setMessage] = useState(''); return <Screen style={styles.auth}><Text style={common.title}>Nova senha</Text><Text style={common.subtitle}>Use o código recebido e escolha uma senha segura.</Text><Input label="Código de recuperação" value={token} onChangeText={setToken} autoCapitalize="none" /><Input label="Nova senha" value={senha} onChangeText={setSenha} secureTextEntry /><Button title="Salvar nova senha" onPress={async () => { try { await authApi.resetPassword(token, senha); setMessage('Senha atualizada. Você já pode entrar.'); } catch (e) { setMessage(e.message); } }} />{message ? <Text style={styles.message}>{message}</Text> : null}<Button title="Voltar ao login" variant="ghost" onPress={() => go('login')} /></Screen>; }
const styles = StyleSheet.create({ auth: { justifyContent: 'center', flexGrow: 1, gap: spacing.md }, brand: { color: colors.primary, fontSize: 13, letterSpacing: 2, fontWeight: '900', marginBottom: 10 }, center: { textAlign: 'center', color: colors.muted }, message: { color: colors.success, textAlign: 'center', lineHeight: 20 } });
