/* eslint-disable react-hooks/set-state-in-effect, react-hooks/purity */
import React, { useCallback, useEffect, useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, EmptyState, ErrorState, Skeleton } from '../components/ui';
import { documentsApi } from '../services/api';
import { colors, common, spacing } from '../theme';
import { date } from './shared';
export default function Deadlines() { const [items, setItems] = useState(); const [error, setError] = useState(''); const load = useCallback(async () => { try { setError(''); setItems((await documentsApi.deadlines()).deadlines || []); } catch (e) { setError(e.message); } }, []); useEffect(() => { load(); }, [load]); if (error) return <ScrollView style={common.screen}><ErrorState error={error} retry={load} /></ScrollView>; if (!items) return <ScrollView contentContainerStyle={styles.content}><Skeleton height={30} /><Skeleton height={90} /></ScrollView>; const groups = { Hoje: [], 'Esta semana': [], Depois: [] }; items.forEach(x => { const diff = Math.ceil((new Date(x.due_date) - Date.now()) / 86400000); groups[diff <= 0 ? 'Hoje' : diff <= 7 ? 'Esta semana' : 'Depois'].push(x); }); return <ScrollView style={common.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={false} onRefresh={load} tintColor={colors.primary} />}><Text style={common.title}>Prazos</Text>{items.length === 0 ? <EmptyState title="Sua agenda está livre" text="Prazos identificados nos documentos aparecerão aqui." /> : Object.entries(groups).map(([group, list]) => list.length ? <View key={group} style={styles.group}><Text style={common.sectionTitle}>{group}</Text>{list.map(item => { const urgent = Math.ceil((new Date(item.due_date) - Date.now()) / 86400000) <= 3; return <Card key={item.id} style={styles.card}><View><Text style={styles.name}>{item.description}</Text><Text style={styles.file}>{item.original_name}</Text></View><View style={[styles.badge, { backgroundColor: urgent ? '#F59E0B22' : '#3B82F622' }]}><Text style={{ color: urgent ? colors.warning : colors.primary, fontWeight: '800' }}>{date(item.due_date)}</Text></View></Card>; })}</View> : null)}</ScrollView>; }
const styles = StyleSheet.create({ content: { padding: spacing.lg, paddingBottom: 130, gap: spacing.lg }, group: { gap: spacing.sm }, card: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, name: { color: colors.text, fontWeight: '700' }, file: { color: colors.muted, marginTop: 4, fontSize: 12 }, badge: { padding: 9, borderRadius: 10 } });
