import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text } from 'react-native';
import { Button, EmptyState, ErrorState, Input, Skeleton } from '../components/ui';
import { documentsApi } from '../services/api';
import { colors, common, spacing } from '../theme';
import { DocumentCard } from './sharedV2';

export default function DocumentsV2({ openDocument }) { const [documents, setDocuments] = useState(); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [type, setType] = useState('todos'); const [deleting, setDeleting] = useState(null); const load = useCallback(async () => { try { setError(''); setDocuments(await documentsApi.list()); } catch (err) { setError(err.message); } }, []); useEffect(() => { load(); }, [load]); const remove = async (id) => { if (deleting) return; setDeleting(id); try { await documentsApi.remove(id); setDocuments((current) => current.filter((item) => item.id !== id)); } catch (err) { setError(err.message || 'Não foi possível excluir o documento.'); } finally { setDeleting(null); } }; const filtered = useMemo(() => (documents || []).filter((doc) => (type === 'todos' || doc.document_type === type) && doc.original_name.toLowerCase().includes(query.toLowerCase())), [documents, query, type]); if (error && !documents) return <ScrollView style={common.screen}><ErrorState error={error} retry={load} /></ScrollView>; if (!documents) return <ScrollView contentContainerStyle={styles.content}><Skeleton height={52} /><Skeleton height={100} /></ScrollView>; return <ScrollView style={common.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={false} onRefresh={load} tintColor={colors.primary} />}><Text style={common.title}>Documentos</Text>{error ? <ErrorState error={error} retry={() => { setError(''); load(); }} /> : null}<Input label="Buscar documentos" value={query} onChangeText={setQuery} placeholder="Nome do arquivo" icon="⌕" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{['todos', 'contrato', 'exame', 'boleto', 'termo_de_uso', 'outro'].map((value) => <Button key={value} title={value === 'todos' ? 'Todos' : value.replaceAll('_', ' ')} variant={type === value ? 'primary' : 'secondary'} onPress={() => setType(value)} style={styles.filter} />)}</ScrollView>{filtered.length ? filtered.map((doc) => <DocumentCard key={doc.id} document={doc} onPress={() => openDocument(doc.id)} onDelete={() => remove(doc.id)} deleting={deleting === doc.id} />) : <EmptyState title="Nenhum documento encontrado" text="Envie um documento para começar." />}</ScrollView>; }
const styles = StyleSheet.create({ content: { padding: spacing.lg, paddingBottom: 130, gap: spacing.md }, filters: { gap: spacing.xs }, filter: { minHeight: 40 } });
