/* eslint-disable react-hooks/set-state-in-effect */
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, RefreshControl, ScrollView, StyleSheet, Text } from 'react-native';
import { Button, EmptyState, ErrorState, Input, Skeleton } from '../components/ui';
import { documentsApi } from '../services/api';
import { colors, common, spacing } from '../theme';
import { DocumentCard } from './sharedV2';
export default function Documents({ openDocument }) { const [docs, setDocs] = useState(); const [error, setError] = useState(''); const [q, setQ] = useState(''); const [type, setType] = useState('todos'); const load = useCallback(async () => { try { setError(''); setDocs(await documentsApi.list()); } catch (e) { setError(e.message); } }, []); useEffect(() => { load(); }, [load]); const filtered = useMemo(() => (docs || []).filter(d => (type === 'todos' || d.document_type === type) && d.original_name.toLowerCase().includes(q.toLowerCase())), [docs, q, type]); const remove = id => Alert.alert('Excluir documento?', 'O arquivo e suas análises serão removidos.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { try { await documentsApi.remove(id); load(); } catch (e) { Alert.alert('Não foi possível excluir', e.message); } } }]); if (error) return <ScrollView style={common.screen}><ErrorState error={error} retry={load} /></ScrollView>; if (!docs) return <ScrollView contentContainerStyle={styles.content}><Skeleton height={50} /><Skeleton height={100} /></ScrollView>; return <ScrollView style={common.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={false} onRefresh={load} tintColor={colors.primary} />}><Text style={common.title}>Documentos</Text><Input label="Buscar documentos" value={q} onChangeText={setQ} icon="⌕" placeholder="Nome do arquivo" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{['todos', 'contrato', 'exame', 'boleto', 'termo_de_uso', 'outro'].map(v => <Button key={v} title={v === 'todos' ? 'Todos' : v.replaceAll('_', ' ')} variant={type === v ? 'primary' : 'secondary'} onPress={() => setType(v)} style={styles.filter} />)}</ScrollView>{filtered.length ? filtered.map(d => <DocumentCard key={d.id} document={d} onPress={() => openDocument(d.id)} onDelete={() => remove(d.id)} />) : <EmptyState title="Nenhum documento encontrado" text="Ajuste sua busca ou envie um novo arquivo." />}</ScrollView>; }
const styles = StyleSheet.create({ content: { padding: spacing.lg, paddingBottom: 130, gap: spacing.md }, filters: { gap: spacing.xs }, filter: { minHeight: 40 } });
