import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Trash2 } from 'lucide-react-native';
import { Badge, Card } from '../components/ui';
import { colors, spacing } from '../theme';
import { date, typeLabel } from './shared';

export function DocumentCard({ document, onPress, onDelete, deleting }) { return <Card style={styles.card}><Pressable accessibilityRole="button" accessibilityLabel={`Abrir ${document.original_name}`} onPress={onPress} style={({ pressed, hovered }) => [styles.main, pressed && styles.pressed, hovered && styles.hover]}><View style={styles.file}><Text style={styles.fileLabel}>{document.mime_type?.startsWith('image') ? 'IMG' : 'PDF'}</Text></View><View style={styles.info}><Text numberOfLines={1} style={styles.name}>{document.original_name}</Text><Text style={styles.meta}>{typeLabel[document.document_type] || 'Documento'} · {date(document.created_at)}</Text></View><Badge status={document.status} /></Pressable>{onDelete && <Pressable disabled={deleting} accessibilityRole="button" accessibilityLabel={`Excluir ${document.original_name}`} onPress={onDelete} style={[styles.delete, deleting && styles.deleteDisabled]}><Trash2 size={16} color={colors.error} /><Text style={styles.deleteText}>{deleting ? 'Excluindo…' : 'Excluir'}</Text></Pressable>}</Card>; }
const styles = StyleSheet.create({ card: { gap: spacing.xs }, main: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 52, borderRadius: 14 }, pressed: { transform: [{ scale: .98 }] }, hover: { backgroundColor: '#3B82F611' }, file: { width: 42, height: 42, borderRadius: 12, backgroundColor: '#3B82F622', alignItems: 'center', justifyContent: 'center' }, fileLabel: { color: colors.primary, fontSize: 10, fontWeight: '800' }, info: { flex: 1, minWidth: 0 }, name: { color: colors.text, fontWeight: '700', fontSize: 15 }, meta: { color: colors.muted, fontSize: 12, marginTop: 3 }, delete: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', gap: 5, minHeight: 44, paddingHorizontal: 8 }, deleteDisabled: { opacity: .5 }, deleteText: { color: colors.error, fontSize: 12, fontWeight: '700' } });
