import React, { useEffect, useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import { CloudUpload, Trash2 } from 'lucide-react-native';
import { Button, Card, Screen } from '../components/ui';
import { documentsApi, userApi } from '../services/api';
import { colors, common, spacing } from '../theme';

const types = ['contrato', 'exame', 'boleto', 'termo_de_uso', 'outro'];
const steps = [{ key: 'queued', label: 'Enviado' }, { key: 'processing', label: 'Extraindo texto' }, { key: 'extracted', label: 'Texto extraído' }, { key: 'analyzing', label: 'Analisando com IA' }, { key: 'done', label: 'Pronto' }];
export default function UploadV2({ navigate }) { const [file, setFile] = useState(); const [type, setType] = useState('contrato'); const [consent, setConsent] = useState(false); const [sending, setSending] = useState(false); const [document, setDocument] = useState(); const pick = async (mode) => { let asset; if (mode === 'file') { const result = await DocumentPicker.getDocumentAsync({ type: ['application/pdf', 'image/jpeg', 'image/png'], copyToCacheDirectory: true }); if (!result.canceled) asset = result.assets[0]; } else { const permission = mode === 'camera' ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('Permissão necessária', 'Permita o acesso para selecionar ou digitalizar o documento.'); const result = mode === 'camera' ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: .9 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: .9 }); if (!result.canceled) asset = result.assets[0]; } if (!asset) return; const size = asset.size || asset.fileSize || 0; if (size > 10 * 1024 * 1024) return Alert.alert('Arquivo muito grande', 'Envie PDF, JPG ou PNG de até 10 MB.'); setFile({ uri: asset.uri, name: asset.name || asset.fileName || 'documento.jpg', type: asset.mimeType || asset.type || 'image/jpeg', size, webFile: asset.file }); };
  const send = async () => { if (!file || !consent) return; setSending(true); try { await userApi.consent(); const response = await documentsApi.upload(file.webFile || { uri: file.uri, name: file.name, type: file.type }, type); setDocument(response.documento); } catch (error) { Alert.alert('Não foi possível enviar', error.message); } finally { setSending(false); } };
  useEffect(() => { if (!document?.id || ['done', 'failed'].includes(document.status)) return undefined; const timer = setInterval(async () => { try { setDocument(await documentsApi.detail(document.id)); } catch (error) { clearInterval(timer); } }, 3000); return () => clearInterval(timer); }, [document?.id, document?.status]);
  if (document) { const current = steps.findIndex((step) => step.key === document.status); const failed = document.status === 'failed'; return <Screen><Text style={common.title}>{failed ? 'Não foi possível concluir' : document.status === 'done' ? 'Documento analisado' : 'Processando documento'}</Text><Card style={styles.timeline}>{steps.map((step, index) => <View key={step.key} style={styles.step}><View style={[styles.dot, index <= current && styles.dotDone, failed && styles.dotFailed]} /><Text style={styles.stepText}>{step.label}</Text></View>)}</Card>{failed ? <><Text style={styles.error}>{document.error_message || 'Tente novamente.'}</Text><Button title="Tentar novamente" onPress={async () => { try { await documentsApi.retry(document.id); setDocument({ ...document, status: 'queued' }); } catch (error) { Alert.alert('Erro', error.message); } }} /></> : <Text style={common.subtitle}>{document.status === 'done' ? 'Sua análise está disponível na lista de documentos.' : 'Acompanhe o progresso; você não precisa reabrir o app.'}</Text>}<Button title="Ir para documentos" variant="secondary" onPress={() => navigate('documents')} /></Screen>; }
  return <Screen><Text style={common.title}>Enviar documento</Text><Text style={common.subtitle}>PDF, JPG ou PNG de até 10 MB.</Text><Card style={styles.drop}><CloudUpload size={38} color={colors.primary} /><Text style={styles.fileName}>{file?.name || 'Escolha um arquivo'}</Text><Text style={styles.fileMeta}>{file ? `${Math.ceil(file.size / 1024)} KB` : 'Seus documentos são enviados com segurança.'}</Text>{file?.type?.startsWith('image') && <Image source={{ uri: file.uri }} style={styles.preview} />}{file && <Pressable accessibilityLabel="Remover arquivo" onPress={() => setFile(undefined)} style={styles.remove}><Trash2 size={18} color={colors.error} /><Text style={styles.removeText}>Remover</Text></Pressable>}</Card><View style={styles.sources}><Button title="Arquivo" variant="secondary" onPress={() => pick('file')} style={styles.source} /><Button title="Fotos" variant="secondary" onPress={() => pick('image')} style={styles.source} /><Button title="Câmera" variant="secondary" onPress={() => pick('camera')} style={styles.source} /></View><Text style={common.sectionTitle}>Tipo do documento</Text><View style={styles.chips}>{types.map((item) => <Pressable key={item} onPress={() => setType(item)} accessibilityRole="radio" accessibilityState={{ selected: type === item }} style={[styles.chip, type === item && styles.chipOn]}><Text style={[styles.chipText, type === item && styles.chipTextOn]}>{item.replaceAll('_', ' ')}</Text></Pressable>)}</View><Pressable onPress={() => setConsent(!consent)} accessibilityRole="checkbox" accessibilityState={{ checked: consent }} style={styles.consent}><View style={[styles.checkbox, consent && styles.checkboxOn]}>{consent && <Text style={styles.check}>✓</Text>}</View><Text style={styles.consentText}>Autorizo o processamento deste documento conforme a política de privacidade.</Text></Pressable><Button title="Enviar para análise" disabled={!file || !consent} loading={sending} onPress={send} /></Screen>; }
const styles = StyleSheet.create({ drop: { alignItems: 'center', gap: spacing.xs, borderStyle: 'dashed' }, fileName: { color: colors.text, fontSize: 16, fontWeight: '700' }, fileMeta: { color: colors.muted, textAlign: 'center' }, preview: { width: '100%', height: 150, borderRadius: 12, marginTop: 8 }, remove: { flexDirection: 'row', alignItems: 'center', gap: 6, padding: 8 }, removeText: { color: colors.error, fontWeight: '700' }, sources: { flexDirection: 'row', gap: spacing.xs }, source: { flex: 1 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, chip: { borderRadius: 18, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12, paddingVertical: 9, backgroundColor: colors.surface }, chipOn: { borderColor: colors.primary, backgroundColor: '#3B82F622' }, chipText: { color: colors.muted, textTransform: 'capitalize', fontSize: 13 }, chipTextOn: { color: colors.primary, fontWeight: '700' }, consent: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center', minHeight: 44 }, checkbox: { width: 22, height: 22, borderRadius: 6, borderColor: colors.muted, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, checkboxOn: { borderColor: colors.primary, backgroundColor: colors.primary }, check: { color: colors.white, fontWeight: '800' }, consentText: { color: colors.muted, flex: 1, fontSize: 13, lineHeight: 19 }, timeline: { gap: spacing.md }, step: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, dot: { width: 14, height: 14, borderRadius: 7, backgroundColor: colors.border }, dotDone: { backgroundColor: colors.success }, dotFailed: { backgroundColor: colors.error }, stepText: { color: colors.text, fontWeight: '600' }, error: { color: colors.error, lineHeight: 20 } });
